### ISSUE TITLE
如果 keymap 是 Mac OX 10.5 +

### ISSUE THREAD

**Issue by tyzero** [Skykai521/ECTranslation#1]
如果 keymap 是 Mac OX 10.5 +，翻译的默认的快捷键是control + I ，用不了。
我把他手动修改成 comand +I 才行

比较喜欢喜欢MacOS 这套键位，适合苹果系统

**Comment by Skykai521** [comment]
快捷键我觉得还是每个人都有一个适合的，我自己用的也不是command+ I 。。。但是如果有大多数人都推荐的快捷键。到时候会改成默认的。
