### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jokerZOc** [Skykai521/ECTranslation#12]
左键双击作为快捷键触发的话就会遇到一个问题，就是你想打开目录结构的话，双击只能变成单击箭头了
![image](https://cloud.githubusercontent.com/assets/16160722/15385590/27da8b1a-1dd5-11e6-8684-a9ad2ffb1472.png)这真是令人蛋疼的一个问题

**Comment by Skykai521** [comment]
确实有这样的问题，所以还是推荐设置键盘快捷键
