### ISSUE TITLE
建议：把左边的感叹号去掉会不会更加简洁优雅一些

### ISSUE THREAD

**Issue by snowjade** [Skykai521/ECTranslation#14]
![image](https://cloud.githubusercontent.com/assets/11959369/15467175/b965708a-210f-11e6-9429-8b4180fcce55.png)

如果技术允许的话，把左边的感叹号去掉会不会更加简洁优雅一些？为什么选择一个感叹号作为翻译功能的图标呢？

**Comment by Skykai521** [comment]
现在还没找到隐藏的方法，找到之后会去掉的。可以先watch项目，有更新会有邮件提醒

**Comment by Skykai521** [comment]
1.3版本已经去除，[点击下载](https://github.com/Skykai521/ECTranslation/releases)
