### ISSUE TITLE
默认快捷键shift＋Ｔ导致无法输入大写Ｔ

### ISSUE THREAD

**Issue by artharyoung** [Skykai521/ECTranslation#17]
windows平台，导入插件后默认快捷方式是shift＋Ｔ，这就导致了在编写代码按住shift无法输入大写的Ｔ。这个问题更改快捷键可以解决。
我试了一下Alt＋Ｔ快捷键并没有在使用
建议默认快捷键更改为Alt＋Ｔ。

**Comment by Skykai521** [comment]
默认的快捷键设置的确实不够人性化，但是基本上每个人都会改成适合自己的快捷键。后面可能会更换成Alt + T
