### ISSUE TITLE
连接超时怎么解决

### ISSUE THREAD

**Issue by WangShang1** [Skykai521/ECTranslation#28]
![image](https://cloud.githubusercontent.com/assets/18344354/17168861/454d54b6-5417-11e6-93b4-31cf75e6db4b.png)

**Comment by Skykai521** [comment]
我这边也是连接超时了，要么是有道的服务器出问题了，要么是key被封了。。。

**Comment by WangShang1** [comment]
连接超时，pc装了有道翻译，开了Lantern，不知是何原因

**Comment by Skykai521** [comment]
现在已经好了，有时候有道翻译会抽风
