### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by PoppinDevil** [Skykai521/ECTranslation#3]
你好，很感谢你提供这么好的插件工具。我在Android studio 2.0 release上安装了。可以正常翻译，但是在音标部分出现了乱码，是不是我哪里的环境配置没有配好？
如图：
![1](https://cloud.githubusercontent.com/assets/5470152/15313073/64916d94-1c3b-11e6-9b22-2b68ed14ab28.jpg)

**Comment by Skykai521** [comment]
这个我也暂时不知道什么原因，可能是你电脑上字库的原因。具体原因还需要查

**Comment by PoppinDevil** [comment]
win7正版系统，没有折腾过字体，只是把IDE的字体改成了Source Code Pro。不是这个原因，我已经试过。

**Comment by jokerZOc** [comment]
@PoppinDevil 改成别的字体即可
