### ISSUE TITLE
只能在mac上使用？

### ISSUE THREAD

**Issue by kongkong0929** [Skykai521/ECTranslation#4]
如题

**Comment by Skykai521** [comment]
Mac和 Windows都可以使用，使用方法一样

**Comment by kongkong0929** [comment]
“选中代码,选择 Edit -> Translate”  右键代码没有看到edit这个选项呢

**Comment by Skykai521** [comment]
是顶部菜单栏的 Edit 里

**Comment by kongkong0929** [comment]
请问win下的快捷键是？ meta+i? meta是哪个

**Comment by Skykai521** [comment]
应该是ctrl，你可以自己修改快捷键的。在项目的README里有写 [修改快捷键](https://github.com/Skykai521/ECTranslation#修改快捷键)

**Comment by kongkong0929** [comment]
ctrl不行呢 我试试修改快捷键，谢谢

**Comment by HJXANDHMR** [comment]
Window 下是Shift +T。太好用了。

**Comment by nadazero** [comment]
首页的说明是针对Mac的情况
Win和Mac还是有些区别的，原理都是一样的，大家自己摸索吧。
