### ISSUE TITLE
你好，我AS是2.3的，设置快捷键和直接在edit栏点击翻译都出现NullPointerException: null

### ISSUE THREAD

**Issue by ZengFanzai** [Skykai521/ECTranslation#42]
同题，请大神赐教，谢谢！

**Comment by 18911006322** [comment]
一样出现。

**Comment by ZengFanzai** [comment]
我换成那个translation那个插件

**Comment by Skykai521** [comment]
是无论如何怎么翻译都无法识别吗?马上会排查更新

**Comment by cxMax** [comment]
2.3 beta 1 也存在这个问题

**Comment by Fomove** [comment]
同问～android studio 2.3出现NullPointerException: null

**Comment by Skykai521** [comment]
是1.4版本吗?

**Comment by Fomove** [comment]
1.3版本
@Skykai521

**Comment by Skykai521** [comment]
试试1.4版本看看行不行

**Comment by Fomove** [comment]
1.3和1.4版本在Android Studio2.3 Beta 1还是会出现NullPointerException: null
@Skykai521

**Comment by Skykai521** [comment]
知道了 谢谢，可能是Android Studio  2.3的部分插件API有变化导致空指针异常，会尽快排查。

**Comment by relice** [comment]
2.3同样有这个问题

**Comment by Skykai521** [comment]
1.5版本已经修复，下载最新的[ECTranslation1.5.jar](https://github.com/Skykai521/ECTranslation/blob/master/ECTranslation1.5.jar)即可，稍后更新到Plugin仓库

**Comment by fashare2015** [comment]
请教一下，这个空指针怎么解决的，我自己开发的插件也是在As2.3上，一点按钮就空指针。

**Comment by ZengFanzai** [comment]
这个软件的开发者还没给我回复，我也不知道


发自网易邮箱大师

在2017年10月16日 11:32，梁山boy<notifications@github.com><mailto:notifications@github.com> 写道：

请教一下，这个空指针怎么解决的，我自己开发的插件也是在As2.3上，一点按钮就空指针。
