### ISSUE TITLE
报个BUG

### ISSUE THREAD

**Issue by GavinAndre** [Skykai521/ECTranslation#5]
使用快捷键一直按着的话会不停的新建实例导致假死
还有提个建议 翻译提示的持续时间太短没看完翻译就消失了，希望快捷键长按的话能让翻译窗口不消失而且不会不停新建翻译窗口实例而导致假死

**Comment by Skykai521** [comment]
嗯，感谢提bug。在下一步的优化计划里。另外欢迎一起完善ECTranslation。

**Comment by Skykai521** [comment]
Fixed in 1.1
