### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by jokerZOc** [Skykai521/ECTranslation#6]
![qq 20160518075307](https://cloud.githubusercontent.com/assets/16160722/15343236/b84bfea8-1ccd-11e6-8a05-4ceb612e5da3.png)
你好，完全乱码

**Comment by jokerZOc** [comment]
你好，问题已经查到，字体设置问题，Appearance&Behavior->Appearance->UI Options->Name里面设置一下别的字体即可

**Comment by Skykai521** [comment]
知道了，谢谢反馈，稍后会更新到README里

**Comment by jokerZOc** [comment]
@Skykai521 不客气，应该的

**Comment by a995171801** [comment]
翻译窗口停顿时间有点短，能不能跟sutido一样，点击提示窗口，长时间停留

**Comment by jokerZOc** [comment]
@a995171801 如果我没猜错就是src->RequestRunnable第80行的3000，改大点就是了，用IDEA自己编译一个jar包

**Comment by a995171801** [comment]
ok

**Comment by Skykai521** [comment]
对的，如果大家都反映消失时间比较快的话，下个版本就增加停留时间

**Comment by lusain1990** [comment]
增加停留时间吧
因为有的文档是长句

**Comment by Skykai521** [comment]
1.2版本已经发布，增加了停留时间，并且现在支持拆分单词翻译，比如：setContentView与ALIGN_CENTER的翻译了。

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by NaughtyChild** [comment]
你好，能不能增加popwindow的停留时间，或者说点击快捷键显示popwindow显示，点击popwindow外侧关闭，因为想一边来开发一边来学习英语，显示时时间希望长一点，谢谢作者，作者辛苦了。版本1.3

**Comment by androidlli** [comment]
提示显示的时间还是少啊，我用的1.3的，最好能焦点在上面的时候就一直显示。

**Comment by userjack** [comment]
![image](https://cloud.githubusercontent.com/assets/11630996/15733755/d89a0700-28bb-11e6-8c50-c0eb4a5feec6.png)
你好乱码怎么解决？“我换成其他的字体也是一样的

**Comment by androidlli** [comment]
不知道。。我的没遇到。。。问下作者。




在 2016-06-02 12:17:21，"userjack" <notifications@github.com> 写道：



你好乱码怎么解决？“我换成其他的字体也是一样的

**Comment by Skykai521** [comment]
应该是字体的原因，具体我也没遇到过 不太清楚。。。

**Comment by BBcaptain** [comment]
我换成微软雅黑的就没出现乱码的现象了

**Comment by scdandanmian** [comment]
大神能增加发音功能吗.想多学学英语

**Comment by Zccf** [comment]
大神能增加发音功能吗.想多学学英语,建立单词本,在提示框里面可以添加单词到单词本

**Comment by dangmeng** [comment]
乱码 改了字体还是乱码!

**Comment by wlwanglun** [comment]
只有设置成 中文字体(比如 楷体,宋体)的时候翻译显示才不会乱码.设置成英文的那种 就会乱码(比如 segoeui 等)

**Comment by GaryPiter** [comment]
![15](https://cloud.githubusercontent.com/assets/17326782/19225745/f7e8d3ba-8ed3-11e6-8f7f-a0a805ea5c02.jpg)
为什么我装不上n呢

**Comment by pumatus** [comment]
nice!

**Comment by Chan2U** [comment]
![image](https://cloud.githubusercontent.com/assets/15801698/22060013/276fa0da-ddaa-11e6-8aea-d4a42a264681.png)
翻译出现这个

**Comment by DeveloperZhuG** [comment]
Appearance&Behavior->Appearance->UI Options->Name里面选择Microsoft YaHei就可以啦，我只尝试了这一种字体，就解决了乱码。其他的字体我没有测试

**Comment by zhanlv** [comment]
出现了乱码,有解吗?不喜欢用微软雅黑.
