### ISSUE TITLE
注册双击左键监听之后, 无法打开导航栏的文件

### ISSUE THREAD

**Issue by lixingmao** [Skykai521/ECTranslation#7]
设置快捷键, 鼠标监听, 左键双击, 到时左侧导航栏的文件双击无法打开...

**Comment by Skykai521** [comment]
确实有这样的问题，所以还是推荐不设置鼠标快捷键。

**Comment by lixingmao** [comment]
不能只监听鼠标在编辑区时对应的鼠标事件吗?  编辑区以外交给系统...  不是是否容易实现?😊

**Comment by nadazero** [comment]
汗，还好上来看了issue list，感觉问题还比较多。感觉还是鼠标双击比较方便，希望作者能改善这个问题。
吐槽一下，为什么没有鼠标三击的事件呢？有的话就好了

**Comment by Skykai521** [comment]
由于是Android Studio提供的快捷键设置，暂时没有找到可以解决的办法，所以还是推荐设置键盘快捷键
